language: php

php:
  - 7.3
  - 7.3.5

before_script:
  - cp .env.travis .env
  - composer install --no-interaction

script:
  - php artisan key:generate
  - vendor/bin/phpunit

services: -redis-server

cache:
  directories:
    - vendor
